# Site settings
title: Steven Thurlow - sthurlow.com
email: steven@sthurlow.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sthurlow.com" # the base hostname & protocol for your site
twitter_username: stoive
github_username:  stoive

permalink: /categories/:year-:month-:day-:title.html

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
#      permalink: /:categories/:title-:short_year:month:day.html
      category: posts
      layout: post
